"use client"

import { useEffect } from "react"
import { Metadata } from "next"
import { useRouter } from "next/navigation"
import { Separator } from "@radix-ui/react-separator"

import { useTokenStore } from "@/store/use-token-store"
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb"
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar"
import { Toaster } from "@/components/ui/toaster"
import { AppSidebar } from "@/components/app-sidebar"

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
}

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const router = useRouter()
  const { loadTokenFromStorage, isTokenValid, clearToken } = useTokenStore()

  useEffect(() => {
    loadTokenFromStorage()

    if (!isTokenValid()) {
      clearToken()
      router.push("/login")
    }
  }, [clearToken, isTokenValid, loadTokenFromStorage, router])

  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
          <div className="flex items-center gap-2 px-4">
            <SidebarTrigger className="-ml-1" />
            <Separator orientation="vertical" className="mr-2 h-4" />
            <Breadcrumb>
              <BreadcrumbList>
                <BreadcrumbItem className="hidden md:block">
                  <BreadcrumbLink href="#">
                    Building Your Application
                  </BreadcrumbLink>
                </BreadcrumbItem>
                <BreadcrumbSeparator className="hidden md:block" />
                <BreadcrumbItem>
                  <BreadcrumbPage>Data Fetching</BreadcrumbPage>
                </BreadcrumbItem>
              </BreadcrumbList>
            </Breadcrumb>
          </div>
        </header>
        <main>
          <div className="flex flex-1 flex-col gap-4 p-8 pt-0">{children}</div>
        </main>
        <Toaster />
      </SidebarInset>
    </SidebarProvider>
  )
}
